# Generated by Django 5.0.7 on 2024-08-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(editable=False, max_length=160, verbose_name='Slug'),
        ),
    ]
