# Generated by Django 5.0.7 on 2024-08-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(editable=False, max_length=160, unique=True, verbose_name='Slug'),
        ),
    ]
