version: "3.9"

services:
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: kidustore
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin ping -u admin -padmin" ]
      interval: 10s
      timeout: 5s
      retries: 3

  python:
    container_name: python
    restart: always
    build:
      context: .
    volumes:
      - .:/app/code
    command:
      - sh
      - -c
      - python manage.py migrate && python /app/code/manage.py runserver 0:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - python

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  mariadb_data:
  certbot_conf:
  certbot_www:
